# =========================================================
# CONFIGURATION INFORMATION
# =========================================================

# website details

title: Paulo Martins
url: ""
baseurl: ""
site-keywords: personal, porfolio, professional,academia, blog, thought garden
favicon: favicon.ico
favicon48: /assets/icons/png/favicon-48.png

# build configuration
markdown: kramdown

style: /assets/css/style.css
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

feed:
  path: feed.xml
  excerpt_only: true

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  terser_args:                      # Default: (empty)

collections:
  projects:
    output: true
    permalink: /projects/:title/
  blog:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: "_blog"
      type: "blog"
    values:
      layout: blog
      post-image: ""
      description: |
        Default blog entry.
      tags:
        - artificial intelligence
        - machine learning
        - data science
        - philosophy
        - technology
        - ethics
        - reflections
        - commentary
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: project
      project-image: ""
      description: |
        Default project page entry.
      tags:
        - artificial intelligence
        - machine learning
        - data science
        - project
        - academia
        - stem

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore